# Generated by Django 4.2.27 on 2026-01-07 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('numero_interno', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_PROCESO', 'En proceso'), ('OBSERVADO', 'Observado'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado')], default='REGISTRADO', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
